name: Build Examples

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-zephyr:
    container: golioth/golioth-zephyr-base:pr-78-sdk-0.17.4
    strategy:
      matrix:
        include:
          - manifest: west-zephyr.yml
            example: ble_gatt
            board: nrf52840dk/nrf52840
          - manifest: west-ncs.yml
            example: ble_gatt
            board: nrf52840dk/nrf52840
          - manifest: west-zephyr.yml
            example: http_client
            board: frdm_rw612
          - manifest: west-zephyr.yml
            example: http_client
            board: native_sim
            no_sysbuild: true
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: pouch

      - name: Init and update west
        run: |
          west init -l pouch --mf ${{ matrix.manifest }}
          west update --narrow -o=--depth=1

      - name: Install pip packages
        run: |
          uv pip install \
            -r zephyr/scripts/requirements-base.txt        \
            -r zephyr/scripts/requirements-build-test.txt  \
            -r zephyr/scripts/requirements-run-test.txt

          uv pip install \
            -r pouch/requirements-ci-zephyr.txt \
            --require-hashes

      - name: Compile
        shell: bash
        run: |
          if [[ "${{ matrix.no_sysbuild }}" == "true" ]]; then
            SYSBUILD_FLAG=""
          else
            SYSBUILD_FLAG="--sysbuild"
          fi

          west build ${SYSBUILD_FLAG} -p -b ${{ matrix.board }} pouch/examples/zephyr/${{ matrix.example }}

  build-esp-idf:
    strategy:
      matrix:
        include:
          - example: ble_gatt
            target: esp32s3
          - example: http_client
            target: esp32s3
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive

      - name: Build
        uses: espressif/esp-idf-ci-action@e6f5c74232b1ccd4c97ed641f1e48553853f1fd5 # v1.2.0
        with:
          esp_idf_version: v6.0.1
          target: ${{ matrix.target }}
          command: |
            EXAMPLE_APP_PATH=examples/esp_idf/${{ matrix.example }}

            pip install -r requirements-ci-esp-idf.txt

            idf.py -C $EXAMPLE_APP_PATH build
