name: Twister Tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  twister:
    container: golioth/golioth-zephyr-base:sdk-1.0.1
    strategy:
      matrix:
        manifest_yml:
          - west-zephyr
          - west-ncs
      fail-fast: false
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-1.0.1
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: pouch

      - name: Init and update west
        run: |
          west init -l pouch --mf ${{ matrix.manifest_yml }}.yml
          west update --narrow -o=--depth=1

      - name: Install pip packages
        run: |
          uv pip install \
            -r zephyr/scripts/requirements-base.txt        \
            -r zephyr/scripts/requirements-build-test.txt  \
            -r zephyr/scripts/requirements-run-test.txt

          uv pip install \
            -r pouch/requirements-ci-zephyr.txt \
            --require-hashes

      - name: Run tests
        env:
          ZEPHYR_BASE: ${{ github.workspace }}/zephyr
          EXTRA_ZEPHYR_MODULES: ${{ github.workspace }}/pouch
        run: ./zephyr/scripts/twister -v -T pouch/tests

      - name: Collect JUnit Test Report
        if: success() || failure()
        run: |
          cp twister-out/twister_suite_report.xml \
             twister-out/integration-${{ matrix.manifest_yml }}.xml

      - name: Upload CI report summary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: success() || failure()
        with:
          name: ci-summary-integration-${{ matrix.manifest_yml }}
          path: twister-out/integration-${{ matrix.manifest_yml }}.xml
